name: CI

env:
  CI: true

on: [push]

jobs:
  lint:
    # FIXME: Use published version once it's released
    uses: inrupt/javascript-style-configs/.github/workflows/reusable-lint.yml@main

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm test

  e2e-browser:
    # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
    # Since all the other jobs of this workflow depend on this one, skipping it should
    # skip the entire workflow.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Archive browser-based end-to-end test request logs
        uses: actions/upload-artifact@v3
        if: failure()
        continue-on-error: true
        with:
          name: playwright-output
          path: test-results/
