name: CI

env:
  CI: true

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: inrupt/typescript-sdk-tools/.github/workflows/reusable-lint.yml@v1.6.0

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm test
      # Upload coverage for sonarcube (only matching OS and one node version required)
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/

  e2e-browser:
    # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
    # Since all the other jobs of this workflow depend on this one, skipping it should
    # skip the entire workflow.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Archive browser-based end-to-end test request logs
        uses: actions/upload-artifact@v3
        if: failure()
        continue-on-error: true
        with:
          name: playwright-output
          path: test-results/

  sonar-scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
          # is not included the project will show a warning about incomplete information.
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/
      - uses: SonarSource/sonarcloud-github-action@v1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
